### ISSUE TITLE
Memory allocation errors on Polylines and Polygons

### ISSUE THREAD

**Issue by cgreening** [sathibault/vgrs#8] opened 2023-04-28 09:25 UTC
This will recreate the issue. The 16384 number is suspicious...

```
import display

p0 = display.Polyline([386,204,305,248,426,277,406,241,426,248,406,241,386,204], display.WHITE)
p1 = display.Polyline([386,204,171,100,305,248,386,204], display.WHITE)
p2 = display.Polyline([282,300,426,277,305,248,282,300], display.WHITE)
p3 = display.Polyline([386,204,216,55,171,100,386,204], display.WHITE)
p4 = display.Polyline([367,328,426,277,282,300,367,328], display.WHITE)
p5 = display.Polyline([171,100,216,214,305,248,171,100], display.WHITE)
p6 = display.Polyline([216,214,282,300,305,248,216,214], display.WHITE)
p7 = display.Polyline([216,55,171,21,171,100,216,55], display.WHITE)
p8 = display.Polyline([333,313,367,328,282,300,333,313], display.WHITE)
p9 = display.Polyline([333,313,282,300,216,214,171,100,171,21,249,108,289,181,333,313], display.WHITE)
p10 = display.Polyline([171,21,216,55,386,204,249,108,171,21], display.WHITE)
p11 = display.Polyline([426,277,289,181,249,108,386,204,406,241,426,248,406,241,426,277], display.WHITE)
p12 = display.Polyline([333,313,289,181,426,277,367,328,333,313], display.WHITE)
p13 = display.Polyline([255,147,226,185,212,148,233,120,255,147], display.WHITE)
p14 = display.Polyline([265,165,279,202,258,230,236,204,265,165], display.WHITE)
p15 = display.Polyline([199,79,187,95,188,78,199,79], display.WHITE)
p16 = display.Polyline([300,261,299,278,287,277,300,261], display.WHITE)

display.show(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16)
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", in <module>
  File "display.py", in show
MemoryError: memory allocation failed, allocating 16384 bytes
```

**Comment by josuah** [comment] 2023-04-28 11:55
I have first removed the path closing in case there was anything related to it, but it seems like not.

Using this script to incrementally add every set of coordinate until it crashes:
```python
from display import *

coords = (
    (386,204,305,248,426,277,406,241,426,248,406,241),
    (386,204,171,100,305,248),
    (282,300,426,277,305,248),
    (386,204,216,55,171,100),
    (367,328,426,277,282,300),
    (171,100,216,214,305,248),
    (216,214,282,300,305,248),
    (216,55,171,21,171,100),
    (333,313,367,328,282,300),
    (333,313,282,300,216,214,171,100,171,21,249,108,289,181),
    (171,21,216,55,386,204,249,108),
    (426,277,289,181,249,108,386,204,406,241,426,248,406,241),
    (333,313,289,181,426,277,367,328),
    (255,147,226,185,212,148,233,120),
    (265,165,279,202,258,230,236,204),
    (199,79,187,95,188,78),
    (300,261,299,278,287,277),
)

list = []
for co in coords:
    print(co)
    list.append(Polyline(co, WHITE))
    show(list)
```

Result:
```
(386, 204, 305, 248, 426, 277, 406, 241, 426, 248, 406, 241)
(386, 204, 171, 100, 305, 248)
(282, 300, 426, 277, 305, 248)
(386, 204, 216, 55, 171, 100)
Traceback (most recent call last):
  File "<stdin>", in <module>
  File "display.py", in show
MemoryError: memory allocation failed, allocating 16384 bytes
```

So if we try this:
```python
from display import *
list = []
list.append(Polyline((386, 204, 305, 248, 426, 277, 406, 241, 426, 248, 406, 241), WHITE))
list.append(Polyline((386, 204, 171, 100, 305, 248), WHITE))
list.append(Polyline((282, 300, 426, 277, 305, 248), WHITE))
list.append(Polyline((386, 204, 216, 55, 171, 100), WHITE))
show(list)
```

We reproduce the error:
```python
Traceback (most recent call last):
  File "<stdin>", in <module>
  File "display.py", in show
MemoryError: memory allocation failed, allocating 16384 bytes
```

**Comment by josuah** [comment] 2023-04-28 12:02
Although, none of the individual list item seems to trigger the bug, so using a counter to try all combinations:
```python
from display import *

for i in range(0, 1 << 4):
    list = []
    print(f"{i:04b}")
    if 0b0001 & i:
        list.append(Polyline((386, 204, 305, 248, 426, 277, 406, 241, 426, 248, 406, 241), WHITE))
    if 0b0010 & i:
        list.append(Polyline((386, 204, 171, 100, 305, 248), WHITE))
    if 0b0100 & i:
        list.append(Polyline((282, 300, 426, 277, 305, 248), WHITE))
    if 0b1000 & i:
        list.append(Polyline((386, 204, 216, 55, 171, 100), WHITE))
    show(list)
```

It seems that we only fall short on memory while printing them all 4 at once:
```
0000
0001
0010
0011
0100
0101
0110
0111
1000
1001
1010
1011
1100
1101
1110
1111
Traceback (most recent call last):
  File "<stdin>", in <module>
  File "display.py", in show
MemoryError: memory allocation failed, allocating 16384 bytes
```

**Comment by josuah** [comment] 2023-04-28 16:58
The following example from the `dev-display` branch also fails, and has the advantage of being simpler:

It is likely not just the library going out of memory, as it was working before, so there should be enough RAM for handling it all.

```python
import display
poly = display.Polygon([0, 0, 640, 400, 0, 400], display.WHITE)
display.show(poly)
```

And to avoid the edge cases:
```python
import display
poly = display.Polygon([0, 0, 640, 400, 0, 400], display.WHITE)
display.show(poly)
```

**Comment by josuah** [comment] 2023-05-03 13:14
Rather than one individual pattern that makes it fail, it seems like the library uses a bit too much memory in some cases.

It might get improved on a next release.

Something that looks like being the same is also at #3

**Comment by josuah** [comment] 2023-05-05 09:34
With the latest commit, all of the snippets run without crashing!

Although, it shows-up as a tiny polygon.
![mpv-shot0002](https://user-images.githubusercontent.com/55351021/236423362-91404c29-7a37-41ba-95b0-2c78d768b30b.jpg)

So I will try this to see where it stops appearing:

```python
import display
import time

def step(list, coordinates):
    list.append(display.Polyline(coordinates, display.WHITE))
    display.show(list)
    time.sleep(1)

list = []
step(list, [386,204,305,248,426,277,406,241,426,248,406,241,386,204])
step(list, [386,204,171,100,305,248,386,204])
step(list, [282,300,426,277,305,248,282,300])
step(list, [386,204,216,55,171,100,386,204])
step(list, [367,328,426,277,282,300,367,328])
step(list, [171,100,216,214,305,248,171,100])
step(list, [216,214,282,300,305,248,216,214])
step(list, [216,55,171,21,171,100,216,55])
step(list, [333,313,367,328,282,300,333,313])
step(list, [333,313,282,300,216,214,171,100,171,21,249,108,289,181,333,313])
step(list, [171,21,216,55,386,204,249,108,171,21])
step(list, [426,277,289,181,249,108,386,204,406,241,426,248,406,241,426,277])
step(list, [333,313,289,181,426,277,367,328,333,313])
step(list, [255,147,226,185,212,148,233,120,255,147])
step(list, [265,165,279,202,258,230,236,204,265,165])
step(list, [199,79,187,95,188,78,199,79])
step(list, [300,261,299,278,287,277,300,261])
```

**Comment by josuah** [comment] 2023-05-05 09:40
`step(list, [386,204,305,248,426,277,406,241,426,248,406,241,386,204])`
![mpv-shot0017](https://user-images.githubusercontent.com/55351021/236425260-cb756b78-bbd8-4c32-8a66-159c7ccdfda3.jpg)

`step(list, [386,204,171,100,305,248,386,204])`
![mpv-shot0018](https://user-images.githubusercontent.com/55351021/236425265-ba230848-7738-460c-939a-9e64d5e11d4b.jpg)

`step(list, [282,300,426,277,305,248,282,300])`
![mpv-shot0019](https://user-images.githubusercontent.com/55351021/236425270-7c4dbe0b-0b1a-499f-9aa1-3d9f46d3270f.jpg)

`step(list, [386,204,216,55,171,100,386,204])`
![mpv-shot0020](https://user-images.githubusercontent.com/55351021/236425275-8b2385ed-2129-40e9-85a7-04b90dc1741d.jpg)

`step(list, [367,328,426,277,282,300,367,328])`
![mpv-shot0021](https://user-images.githubusercontent.com/55351021/236425282-4f5044d6-1a4a-45af-bb43-caa5c103cfaf.jpg)

`step(list, [171,100,216,214,305,248,171,100])`
![mpv-shot0022](https://user-images.githubusercontent.com/55351021/236425287-39c81996-8269-40e7-a177-cb92a2ea5e0f.jpg)

`step(list, [216,214,282,300,305,248,216,214])`
![mpv-shot0023](https://user-images.githubusercontent.com/55351021/236425293-f57ac52c-1018-4f77-a6d9-fa412672cecb.jpg)

`step(list, [216,55,171,21,171,100,216,55])`
![mpv-shot0024](https://user-images.githubusercontent.com/55351021/236425298-7f8af5eb-3d20-438c-8de7-edbab5b802f8.jpg)

`step(list, [333,313,367,328,282,300,333,313])`
![mpv-shot0025](https://user-images.githubusercontent.com/55351021/236425305-e3a4bcf0-64be-45b8-83a3-8b5268c9b900.jpg)

`step(list, [333,313,282,300,216,214,171,100,171,21,249,108,289,181,333,313])`
![mpv-shot0026](https://user-images.githubusercontent.com/55351021/236425309-65fb58e7-c36a-4972-8f44-dc10a241a81b.jpg)

`step(list, [171,21,216,55,386,204,249,108,171,21])`
![mpv-shot0027](https://user-images.githubusercontent.com/55351021/236425316-a6ff5d62-49c7-4e25-aa75-ac9da1269743.jpg)

And no change for any of:

`step(list, [426,277,289,181,249,108,386,204,406,241,426,248,406,241,426,277])`
`step(list, [333,313,289,181,426,277,367,328,333,313])`
`step(list, [255,147,226,185,212,148,233,120,255,147])`
`step(list, [265,165,279,202,258,230,236,204,265,165])`
`step(list, [199,79,187,95,188,78,199,79])`
`step(list, [300,261,299,278,287,277,300,261])`

At the end, the list is complete though:

```python
>>> list
[Polyline([386,204, 305,248, 426,277, 406,241, 426,248, 406,241, 386,204], 7, thickness=1), Polyline([386,204, 171,100, 305,248, 386,204], 7, thickness=1), Polyline([282,300, 426,277, 305,248, 282,300], 7, thickness=1), Polyline([386,204, 216,55, 171,100, 386,204], 7, thickness=1), Polyline([367,328, 426,277, 282,300, 367,328], 7, thickness=1), Polyline([171,100, 216,214, 305,248, 171,100], 7, thickness=1), Polyline([216,214, 282,300, 305,248, 216,214], 7, thickness=1),
Polyline([216,55, 171,21, 171,100, 216,55], 7, thickness=1), Polyline([333,313, 367,328, 282,300, 333,313], 7, thickness=1), Polyline([333,313, 282,300, 216,214, 171,100, 171,21, 249,108, 289,181, 333,313], 7, thickness=1), Polyline([171,21, 216,55, 386,204, 249,108, 171,21], 7, thickness=1), Polyline([426,277, 289,181, 249,108, 386,204, 406,241, 426,248, 406,241, 426,277], 7,
thickness=1), Polyline([333,313, 289,181, 426,277, 367,328, 333,313], 7, thickness=1), Polyline([255,147, 226,185, 212,148, 233,120, 255,147], 7, thickness=1), Polyline([265,165, 279,202, 258,230, 236,204, 265,165], 7, thickness=1), Polyline([199,79, 187,95, 188,78, 199,79], 7, thickness=1), Polyline([300,261, 299,278, 287,277, 300,261], 7, thickness=1)]
```

**Comment by josuah** [comment] 2023-05-05 11:00
The commented lines are those provoking the error.

```python
import display
import time

def step(list, coordinates):
    list.append(display.Polyline(coordinates, display.WHITE))
    display.show(list)
    time.sleep_ms(300)

list = []
step(list, [386,204,305,248,426,277,406,241,426,248,406,241,386,204])
step(list, [386,204,171,100,305,248,386,204])
step(list, [282,300,426,277,305,248,282,300])
#step(list, [386,204,216,55,171,100,386,204])
step(list, [367,328,426,277,282,300,367,328])
#step(list, [171,100,216,214,305,248,171,100])
#step(list, [216,214,282,300,305,248,216,214])
step(list, [216,55,171,21,171,100,216,55])
#step(list, [333,313,367,328,282,300,333,313])
#step(list, [333,313,282,300,216,214,171,100,171,21,249,108,289,181,333,313])
#step(list, [171,21,216,55,386,204,249,108,171,21])
#step(list, [426,277,289,181,249,108,386,204,406,241,426,248,406,241,426,277])
#step(list, [333,313,289,181,426,277,367,328,333,313])
#step(list, [255,147,226,185,212,148,233,120,255,147])
#step(list, [265,165,279,202,258,230,236,204,265,165])
#step(list, [199,79,187,95,188,78,199,79])
#step(list, [300,261,299,278,287,277,300,261])
```

* Nothing is "corrupted" after this runs: running `list = []` then any valid line works again.
  This suggests it is not due to an invalid state that persists (i.e. memory corruption), but just some other kind of bug.

* Running the problematic lines in any order seems to trigger the problem.

**Comment by josuah** [comment] 2023-05-05 11:07
The smallest reproducer I could get:

```python
step(list, [184,95,188,78]) # ok
step(list, [185,95,188,78]) # ok
step(list, [186,95,188,78]) # ok
step(list, [187,95,188,78]) # err
step(list, [188,95,188,78]) # ok
step(list, [189,95,188,78]) # ok
step(list, [190,95,188,78]) # ok
step(list, [191,95,188,78]) # ok
```

**Comment by josuah** [comment] 2023-05-05 18:51
After https://github.com/sathibault/vgrs/commit/a24e755c9df73ef1eaf992102fa5e2e56b6b148a it works, and it looks nice!

![mpv-shot0002](https://user-images.githubusercontent.com/55351021/236543805-50efa696-8631-4e09-9210-935ce8cc2885.jpg)

**Comment by cgreening** [comment] 2023-05-05 19:04
That's amazing!

**Closed** 2023-05-24 21:21 UTC
